env:
  VALID_QUEUES: 'cat'

agent:
  queues: ${VALID_QUEUES}

steps:
  - command: 'buildkite-agent pipeline upload /Users/roselu/Documents/peanut-bash-example/.buildkite/agent_metadata.yml'
    env:
      VALID_QUEUES: $VALID_QUEUES
